# Generated by Django 5.0.3 on 2024-03-12 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0002_rename_is_publisher_women_is_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='women',
            options={'ordering': ['-time_create']},
        ),
        migrations.AddField(
            model_name='women',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='women',
            index=models.Index(fields=['-time_create'], name='women_women_time_cr_9f33c2_idx'),
        ),
    ]
