# Generated by Django 5.0.3 on 2024-03-13 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0005_alter_women_hasband'),
    ]

    operations = [
        migrations.RenameField(
            model_name='women',
            old_name='hasband',
            new_name='husband',
        ),
    ]
