# Generated by Django 5.0.3 on 2024-03-12 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0006_remove_women_women_women_time_cr_9f33c2_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='women',
            name='women_women_time_cr_21b781_idx',
        ),
        migrations.AddIndex(
            model_name='women',
            index=models.Index(fields=['-time_create'], name='women_women_time_cr_9f33c2_idx'),
        ),
    ]
